package com.example.fico.shared.constants

import com.example.fico.model.ExpenseCategory

class ExpenseCategoriesList {

    companion object {
        val categoryList = listOf(
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.FOOD,
                StringConstants.CATEGORY_LIST.ICON_NAME.FOOD,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.TRANSPORT,
                StringConstants.CATEGORY_LIST.ICON_NAME.TRANSPORT,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.ENTERTAINMENT,
                StringConstants.CATEGORY_LIST.ICON_NAME.ENTERTAINMENT,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.MARKET,
                StringConstants.CATEGORY_LIST.ICON_NAME.MARKET,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.EDUCATION,
                StringConstants.CATEGORY_LIST.ICON_NAME.EDUCATION,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.GIFT,
                StringConstants.CATEGORY_LIST.ICON_NAME.GIFT,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.HEALTHY,
                StringConstants.CATEGORY_LIST.ICON_NAME.HEALTHY,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.GAMES,
                StringConstants.CATEGORY_LIST.ICON_NAME.GAMES,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.INVESTMENT,
                StringConstants.CATEGORY_LIST.ICON_NAME.INVESTMENT,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.ELETRONICS,
                StringConstants.CATEGORY_LIST.ICON_NAME.ELETRONICS,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.REPAIR,
                StringConstants.CATEGORY_LIST.ICON_NAME.REPAIR,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.ACESSORIES,
                StringConstants.CATEGORY_LIST.ICON_NAME.ACESSORIES,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.CLOTHING,
                StringConstants.CATEGORY_LIST.ICON_NAME.CLOTHING,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.CAR,
                StringConstants.CATEGORY_LIST.ICON_NAME.CAR,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.MOTORCYCLE,
                StringConstants.CATEGORY_LIST.ICON_NAME.MOTORCYCLE,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.TRIP,
                StringConstants.CATEGORY_LIST.ICON_NAME.TRIP,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.HOUSE,
                StringConstants.CATEGORY_LIST.ICON_NAME.HOUSE,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.DONATION,
                StringConstants.CATEGORY_LIST.ICON_NAME.DONATION,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.BET,
                StringConstants.CATEGORY_LIST.ICON_NAME.BET,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.PETS,
                StringConstants.CATEGORY_LIST.ICON_NAME.PETS,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.FEES,
                StringConstants.CATEGORY_LIST.ICON_NAME.FEES,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.GYM,
                StringConstants.CATEGORY_LIST.ICON_NAME.GYM,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.CELLPHONE,
                StringConstants.CATEGORY_LIST.ICON_NAME.CELLPHONE,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.PERSONAL_HYGIENE,
                StringConstants.CATEGORY_LIST.ICON_NAME.PERSONAL_HYGIENE,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.PHARMACY,
                StringConstants.CATEGORY_LIST.ICON_NAME.PHARMACY,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.CASH_WITHDRAWAL,
                StringConstants.CATEGORY_LIST.ICON_NAME.CASH_WITHDRAWAL,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.RIDE,
                StringConstants.CATEGORY_LIST.ICON_NAME.RIDE,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.PAYMENT,
                StringConstants.CATEGORY_LIST.ICON_NAME.PAYMENT,
                false
            ),
            ExpenseCategory(
                StringConstants.CATEGORY_LIST.DESCRIPTION.SERVICES,
                StringConstants.CATEGORY_LIST.ICON_NAME.SERVICES,
                false
            )

        )
    }


}